### ISSUE TITLE
module 03 notebook 01_topic_modeling FileNotFoundError

### ISSUE THREAD

**Issue by rbarreto** [dlab-berkeley/Data-Science-Social-Justice-2022#10]
pd.read_csv('aita_sub_top_sm_lemmas.csv') error -- not found 

FileNotFoundError: [Errno 2] File aita_sub_top_sm_lemmas.csv does not exist: 'aita_sub_top_sm_lemmas.csv'

**Comment by pssachdeva** [comment]
you need to include the file in your data directory - it is an output of module 2 (which should be up to date)
