### ISSUE TITLE
Error in training t-SNE

### ISSUE THREAD

**Issue by emilygrabowski** [dlab-berkeley/Data-Science-Social-Justice-2022#18]
Error in following lines:
tsne = TSNE(init='pca', learning_rate='auto')
tsne_vectors = tsne.fit_transform(model.wv.vectors)

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U4'), dtype('float32')) -> None

**Comment by pssachdeva** [comment]
What `gensim` and `sklearn` versions are you running?

**Comment by emilygrabowski** [comment]
gensim: 4.0.0
sklearn: 0.22.1

**Comment by pssachdeva** [comment]
Can you update `sklearn` to >1.0 and try again?

Otherwise, try deleting `learning_rate='auto'`

**Comment by emilygrabowski** [comment]
Updating fixed it! I'll add a note to the sklearn line in the notebook
