### ISSUE TITLE
Module 02 Notebook 03_tf_idf CountVectorizer Error

### ISSUE THREAD

**Issue by rbarreto** [dlab-berkeley/Data-Science-Social-Justice-2022#30]
Under implementing TF-IDF, this line results in an error: pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

this is the error message: 
AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names_out'

**Comment by rbarreto** [comment]
this error persists under the section testing tf-idf with a toy dataset, specifically in this line: pd.DataFrame(word_count_vector.toarray(), columns=cv.get_feature_names_out())

and it may be due to  columns=cv.get_feature_names_out()

**Comment by emilygrabowski** [comment]
I think this one is a version error. I’ve had success changing the line to
.get_feature_names() (removing the ‘out’)

**Comment by pssachdeva** [comment]
We should probably put pip installs for the newer versions of scikit-learn on the DataHub. If this happened on your local machine, I recommend updating your scitkit-learn rather than changing the code.

**Comment by rbarreto** [comment]
this was happening on datahub and my local machine
additionally, i ran re-installed the latest version of scikit-learn and the error persists. 

as emily suggested, changing the line to .get_feature_names() removes the error on both datahub and the local machine

this will need to be changed under the section testing tf-idf with a toy dataset and using TfidfTransformer (twice) as well

**Comment by rbarreto** [comment]
Under Using TF-IDF on Reddit datasets, after changing the method to .get_feature_names() we get an error on this line: columns=tfidf_vectorizer.get_feature_names().ravel())

the error is as follows: AttributeError: 'function' object has no attribute 'ravel'

**Comment by pssachdeva** [comment]
Closed by #40
