### ISSUE TITLE
Module 02 Notebook 01_preprocesssing sns attribute error

### ISSUE THREAD

**Issue by rbarreto** [dlab-berkeley/Data-Science-Social-Justice-2022#32]
(on local machine) 

under the section incorporating time, this line results in an error: sns.set_theme()

this is error:
AttributeError: module 'seaborn' has no attribute 'set_theme'

**Comment by emilygrabowski** [comment]
I think set_theme() requires seaborn 0.11 or newer. Could you check the
version of seaborn on your local machine?

**Comment by pssachdeva** [comment]
Closed by #40
