### ISSUE TITLE
module 01 notebook 02_data_frames

### ISSUE THREAD

**Issue by rbarreto** [dlab-berkeley/Data-Science-Social-Justice-2022#6]
I think the reflection part at the end of the notebook should be highlighted first under the Police Shootings Database. We need to carefully come up with a plan for how to approach that discussion and state our politics up front -- like we ,as scholars, as activists, and as an institution, support Black Lives Matter and recognize that police shootings disproportionately harm Black folks, and that cherry-picked data can be used to erase that fact.

**Comment by pssachdeva** [comment]
Closed by #12
